spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=banking_user
spring.datasource.password=banking_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
