spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/banking_db}
spring.datasource.username=${DATABASE_USERNAME:banking_user}
spring.datasource.password=${DATABASE_PASSWORD:banking_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=900000
server.forward-headers-strategy=framework
server.port=${PORT:8080}
